services:
  - postgresql
addons:
  postgresql: "9.5"
env:
  global:
    - URL=http://localhost:8080
    - PORT=8080
    - NODE_ENV=development
    - PG_HOST=localhost
    - PG_USER=postgres
    - PG_DATABASE=sendit
    - PG_PASSWORD=1234
    - PG_PORT=7777

language: node_js

node_js: 
  - 9
  - node

install:
  - npm install
  - npm install -g express
  - npm install -g request
  - npm install -g @babel/core @babel/cli @babel/node
  - npm install -g jasmine
  - npm install -g jasmine-node
  - npm install -g jasmine-console-reporter
  - npm install -g babel-register
  - npm install -g istanbul

instrumentation:
    root: src

before_script: 
  - psql -c 'CREATE DATABASE sendit
    WITH 
    OWNER = postgres
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;'
  - psql -c 'CREATE TABLE public."order"
    (
    id character(30),
    sender character(20),
    info character(30),
    pickup character(20),
    platitude character(10),
    plongitude character(10),
    destination character(20),
    dlatitude character(10),
    dlongitude character(10),
    current character(20),
    clatitude character(10),
    clongitude character(10),
    weight integer,
    price integer,
    receiver character(20),
    telephone character(15),
    status character(15)
    )';
  - psql -c 'CREATE TABLE public."user"
    (
    id integer,
    name character(20) COLLATE pg_catalog."default",
    sex character(2) COLLATE pg_catalog."default",
    address character(20) COLLATE pg_catalog."default",
    email character(30) COLLATE pg_catalog."default",
    telephone character(15) COLLATE pg_catalog."default",
    username character(20) COLLATE pg_catalog."default",
    password character(20) COLLATE pg_catalog."default",
    token character(50) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id)
    )';

    
script:
  - "npm start &"
  - "npm run delayer"
  - "npm run test2"
  
after_success:
  - codecov
  - "npm run coverage"
