services:
  - postgresql
addons:
  postgresql: "9.5"
env:
  global:
    - URL=http://localhost:8080
    - PORT=8080
    - NODE_ENV=development
    - PG_HOST=localhost
    - PG_USER=postgres
    - PG_DATABASE=sendit
    - PG_PASSWORD=1234
    - PG_PORT=7777
    - DB_HOST=localhost
    - DB_USER=postgres
    - DB_PASS=
    - DB_NAME=sendit
    - DB_PORT=5432

language: node_js

node_js: 
  - 9
  - node

install:
  - npm install
  - npm install -g express
  - npm install -g request
  - npm install -g @babel/core @babel/cli @babel/node
  - npm install -g jasmine
  - npm install -g jasmine-node
  - npm install -g jasmine-console-reporter
  - npm install -g babel-register
  - npm install -g istanbul

instrumentation:
    root: src

    
script:
  - "npm start &"
  - "npm run delayer"
  - "npm run test2"
  - "npm run coverage"
  
after_success:
  - codecov
