const Pool = require('pg').Pool;
import  bodyParser from 'body-parser';
import jwt from 'jsonwebtoken';

export class allidparcelsclass{

    constructor(){

            this.tosendflag=true;
    };

    getallidparcels(request,response){

		    const pool = new Pool({
                user: process.env.DB_USER,
                host: process.env.DB_HOST,
                database: process.env.DB_NAME,
                password: process.env.DB_PASS,
                port: process.env.DB_PORT
              });

            //const sender= request.params.Id;

            jwt.verify(request.token, 'privatekey', (err, authorizedData) => {

            const {token,username}=request.body;

            if(err){

                response.send({token, message: "Your token has a problem.", username});
                response.end(); 
            }
            else
            {
            
            console.log('SELECT * FROM public."order" WHERE "Sender"=\''+username+'\'');
            
            pool.query('SELECT * FROM public."order" WHERE Sender=\''+username+'\'', (error, results) => {
                     if (error) {
                            console.log(error);
                            response.send({token, message: "Server down. Please try later.", username});
                            throw error;
                     }
                     else{
                        let data=results.rows;
                        response.send({token, message: "Parcels generated by User "+username, data, username});
                        response.end();
                     }
            return 0;

            }); 

             }

           });      
	   

    };

}
